apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medinest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TUES-2026-PBL-11-klas/Hospital_Managment_System.git
    targetRevision: HEAD
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hospital-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
