apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - postgres-statefulset.yaml
  - llm-deployment.yaml
  - api-deployment.yaml
  - api-servicemonitor.yaml
  - web-deployment.yaml
  - ingress.yaml
