apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: hospital-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/medinest/postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: hospital-system
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/medinest/ollama
